# Generated by Django 4.0.5 on 2022-06-30 10:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
